name: Flutter

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  flutter_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Flutter action
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-warnings

      - name: Run tests
        run: flutter test
